openapi: 3.1.0

info:
  title: LTA DataMall API
  version: "3.0"
  description: OpenAPI schema for the generated lta-next client.

tags:
  - name: bus
    description: Bus related operations.

  - name: traffic
    description: Traffic related operations.

  - name: taxi
    description: Taxi related operations.

  - name: facility
    description: Facility related operations.

servers:
  - url: https://datamall2.mytransport.sg/ltaodataservice

paths:
  /v3/BusArrival:
    get:
      operationId: getBusArrival
      tags: [bus]
      summary: Get bus arrival timings for a bus stop
      description: >
        Returns real-time Bus Arrival information of Bus Services at a queried Bus Stop,
        including

        - Estimated Arrival Time

        - Estimated Current Location

        - Estimated Current Load.        


        **Update freq**: 20s
      security:
        - accountKeyAuth: []
      parameters:
        - name: BusStopCode
          in: query
          required: true
          description: Bus stop reference code.
          schema:
            $ref: "#/components/schemas/BusStopCode"
          example: "83139"

        - name: ServiceNo
          in: query
          required: false
          description: Optional bus service number filter.
          schema:
            $ref: "#/components/schemas/BusServiceNumber"
          example: "15"

      responses:
        "200":
          description: Successful Bus Arrival response.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BusArrivalResponse"
              example:
                odata.metadata: "https://datamall2.mytransport.sg/ltaodataservice/v3/BusArrival"
                BusStopCode: "83139"
                Services:
                  - ServiceNo: "15"
                    Operator: "GAS"
                    NextBus:
                      OriginCode: "77009"
                      DestinationCode: "77009"
                      EstimatedArrival: "2024-08-14T16:41:48+08:00"
                      Latitude: "1.3154918333333334"
                      Longitude: "103.9059125"
                      VisitNumber: "1"
                      Load: "SEA"
                      Feature: "WAB"
                      Type: "SD"
                      Monitored: "1"
                    NextBus2:
                      OriginCode: "77009"
                      DestinationCode: "77009"
                      EstimatedArrival: "2024-08-14T16:49:22+08:00"
                      Latitude: "1.3309621666666667"
                      Longitude: "103.9034135"
                      VisitNumber: "1"
                      Load: "SEA"
                      Feature: "WAB"
                      Type: "SD"
                      Monitored: "1"
                    NextBus3:
                      OriginCode: "77009"
                      DestinationCode: "77009"
                      EstimatedArrival: "2024-08-14T17:06:11+08:00"
                      Latitude: "1.344761"
                      Longitude: "103.94022316666667"
                      VisitNumber: "1"
                      Load: "SEA"
                      Feature: "WAB"
                      Type: "SD"
                      Monitored: "1"

  /TrafficIncidents:
    get:
      operationId: getTrafficIncidents
      tags: [traffic]
      summary: Get traffic incidents
      description: >
        Returns incidents currently happening on the roads, such as
        Accidents, Vehicle Breakdowns, Road Blocks, Traffic Diversions etc.

        **Update freq**: 2 min
      x-satay:
        output:
          unwrap-field: value
      security:
        - accountKeyAuth: []
      parameters:
        - name: $skip
          in: query
          required: false
          description: Number of records to skip for pagination.
          schema:
            type: integer
            format: uint32
            minimum: 0
          example: 500
      responses:
        "200":
          description: Successful Traffic Incidents response.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TrafficIncidentsResponse"
              example:
                odata.metadata: "https://datamall2.mytransport.sg/ltaodataservice/$metadata#IncidentSet"
                value:
                  - Type: "Roadwork"
                    Latitude: 1.3271784303381247
                    Longitude: 103.73571311990426
                    Message: "Roadworks on AYE (towards Tuas) after Penjuru Rd Exit. Avoid lane 3."

  /Traffic-Imagesv2:
    get:
      operationId: getTrafficImages
      tags: [traffic]
      summary: Get traffic camera images
      description: >
        Returns links to images from traffic cameras located around Singapore,
        together with each camera's location coordinates.

        **Update freq**: 20 sec
      x-satay:
        output:
          unwrap-field: value
      security:
        - accountKeyAuth: []
      parameters:
        - name: $skip
          in: query
          required: false
          description: Number of records to skip for pagination.
          schema:
            type: integer
            format: uint32
            minimum: 0
          example: 500
      responses:
        "200":
          description: Successful Traffic Images response.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TrafficImagesResponse"
              example:
                odata.metadata: "http://datamall2.mytransport.sg/ltaodataservice/$metadata#Traffic-Imagesv2"
                value:
                  - CameraID: "1001"
                    Latitude: 1.29531332
                    Longitude: 103.871146
                    ImageLink: "https://dm-traffic-camera-itsc.s3.ap-southeast-1.amazonaws.com/2023-04-05/23-05/1001_2303_20230405230505_485310.jpg"

  /v3/TrafficSpeedBands:
    get:
      operationId: getTrafficSpeedBands
      tags: [traffic]
      summary: Get traffic speed bands
      description: >
        Returns current traffic speeds on expressways and arterial roads,
        expressed in speed bands.


        **Update freq**: 5 min
      x-satay:
        output:
          unwrap-field: value
      security:
        - accountKeyAuth: []
      parameters:
        - name: $skip
          in: query
          required: false
          description: Number of records to skip for pagination.
          schema:
            type: integer
            format: uint32
            minimum: 0
          example: 500
      responses:
        "200":
          description: Successful Traffic Speed Bands response.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TrafficSpeedBandsResponse"
              example:
                odata.metadata: "http://datamall2.mytransport.sg/ltaodataservice/$metadata#TrafficSpeedBands"
                lastUpdatedTime: "2023-04-05 22:30:00"
                value:
                  - LinkID: "103000000"
                    RoadName: "KENT ROAD"
                    RoadCategory: "E"
                    SpeedBand: 7
                    MinimumSpeed: "60"
                    MaximumSpeed: "69"
                    StartLon: "103.85298052044503"
                    StartLat: "1.3170142376560023"
                    EndLon: "103.85259882242372"
                    EndLat: "1.3166840028663076"

  /BusStops:
    get:
      operationId: getBusStops
      tags: [bus]
      summary: Get bus stops
      description: >
        Returns detailed information for all bus stops currently being serviced by
        buses, including bus stop codes and location coordinates.


        **Update freq**: Ad-Hoc
      x-satay:
        output:
          unwrap-field: value
      security:
        - accountKeyAuth: []
      parameters:
        - name: $skip
          in: query
          required: false
          description: Number of records to skip for pagination.
          schema:
            type: integer
            format: uint32
            minimum: 0
          example: 500
      responses:
        "200":
          description: Successful Bus Stops response.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BusStopsResponse"
              example:
                odata.metadata: "https://datamall2.mytransport.sg/ltaodataservice/$metadata#BusStops"
                value:
                  - BusStopCode: "01012"
                    RoadName: "Victoria St"
                    Description: "Hotel Grand Pacific"
                    Latitude: 1.29684825487647
                    Longitude: 103.85253591654006

  /Taxi-Availability:
    get:
      operationId: getTaxiAvailability
      tags: [taxi]
      summary: Get taxi availability
      description: >
        Returns the coordinates of all taxis currently available for hire.


        **Update freq**: 1 min
      x-satay:
        output:
          unwrap-field: value
      security:
        - accountKeyAuth: []
      parameters:
        - name: $skip
          in: query
          required: false
          description: Number of records to skip for pagination.
          schema:
            type: integer
            format: uint32
            minimum: 0
          example: 500
      responses:
        "200":
          description: Successful Taxi Availability response.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TaxiAvailabilityResponse"
              example:
                odata.metadata: "https://datamall2.mytransport.sg/ltaodataservice/$metadata#TaxiAvailability"
                value:
                  - Longitude: 103.89071
                    Latitude: 1.39588
                  - Longitude: 103.94399
                    Latitude: 1.32122

  /FacilitiesMaintenance:
    get:
      operationId: getFacilitiesMaintenance
      tags: [facility]
      summary: Get facilities maintenance data links
      description: >
        Returns links to facility maintenance data files for a queried MRT/LRT
        station. Each link points to a JSON file describing the maintenance
        works currently in progress at that station.


        **Update freq**: Ad-Hoc
      x-satay:
        output:
          unwrap-field: value
          map-field: Link
      security:
        - accountKeyAuth: []
      parameters:
        - name: StationCode
          in: query
          required: true
          description: MRT/LRT station code.
          schema:
            $ref: "#/components/schemas/StationCode"
          example: "NS1"

      responses:
        "200":
          description: Successful Facilities Maintenance response.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FacilitiesMaintenanceResponse"
              example:
                odata.metadata: "http://datamall2.mytransport.sg/ltaodataservice/$metadata#FacilitiesMaintenance"
                value:
                  - Link: "https://mtmfacilitiesmaintenance.s3.ap-southeast-1.amazonaws.com/NS1.json?X-Amz-Security-Token=EXAMPLE"
                    TimeStamp: "2024-08-14T10:00:00+08:00"

components:
  securitySchemes:
    accountKeyAuth:
      type: apiKey
      in: header
      name: AccountKey
      description: LTA DataMall API account key.

  schemas:
    BusArrivalResponse:
      type: object
      additionalProperties: false
      required:
        - odata.metadata
        - BusStopCode
        - Services
      properties:
        odata.metadata:
          type: string
          format: uri
          description: OData metadata URL.
          x-satay:
            ignore: true

        BusStopCode:
          $ref: "#/components/schemas/BusStopCode"

        Services:
          type: array
          description: Bus services serving the queried bus stop.
          items:
            $ref: "#/components/schemas/BusServiceArrival"

    BusServiceArrival:
      type: object
      additionalProperties: false
      required:
        - ServiceNo
        - Operator
        - NextBus
        - NextBus2
        - NextBus3
      properties:
        ServiceNo:
          $ref: "#/components/schemas/BusServiceNumber"

        Operator:
          $ref: "#/components/schemas/BusOperator"

        NextBus:
          $ref: "#/components/schemas/BusArrivalTiming"
          x-satay:
            treat-error-as-none: true

        NextBus2:
          $ref: "#/components/schemas/BusArrivalTiming"
          x-satay:
            treat-error-as-none: true

        NextBus3:
          $ref: "#/components/schemas/BusArrivalTiming"
          x-satay:
            treat-error-as-none: true

    BusOperator:
      type: string
      description: Public transport operator code.
      enum:
        - SBST
        - SMRT
        - TTS
        - GAS
      example: "SBST"

    BusServiceNumber:
      type: string
      description: Bus service number.
      maxLength: 5
      pattern: "^[a-zA-Z0-9]+$"
      example: "15"

    BusStopCode:
      type: string
      description: Unique 5-digit bus stop reference code.
      pattern: '^\d{5}$'
      example: "83139"
      x-satay:
        parse-as: u32

    BusArrivalTiming:
      type: object
      additionalProperties: false
      required:
        - OriginCode
        - DestinationCode
        - EstimatedArrival
        - Latitude
        - Longitude
        - VisitNumber
        - Load
        - Feature
        - Type
        - Monitored
      properties:
        OriginCode:
          $ref: "#/components/schemas/BusStopCode"

        DestinationCode:
          $ref: "#/components/schemas/BusStopCode"

        EstimatedArrival:
          type: string
          description: Estimated arrival date-time in Singapore Standard Time.
          example: "2024-08-14T16:41:48+08:00"
          x-satay:
            parse-as: offset-datetime

        Latitude:
          type: string
          description: Current estimated latitude of the bus.
          example: "1.3154918333333334"
          x-satay:
            parse-as: f64

        Longitude:
          type: string
          description: Current estimated longitude of the bus.
          example: "103.9059125"
          x-satay:
            parse-as: f64

        VisitNumber:
          type: string
          description: Ordinal visit number of this vehicle at the bus stop.
          example: "1"
          x-satay:
            parse-as: u8

        Load:
          type: string
          description: Current occupancy level.
          enum:
            - SEA
            - SDA
            - LSD
            - ""
          x-satay:
            enum-variants:
              SEA: SeatsAvailable
              SDA: StandingAvailable
              LSD: LimitedStanding
              "": Unspecified

        Feature:
          type: string
          description: Wheelchair accessibility indicator.
          enum:
            - WAB
            - ""
          x-satay:
            enum-variants:
              WAB: WheelchairAccessible
              "": Unspecified

        Type:
          type: string
          description: Vehicle type of the bus.
          enum:
            - SD
            - DD
            - BD
            - ""
          x-satay:
            enum-variants:
              SD: SingleDecker
              DD: DoubleDecker
              BD: Bendy
              "": Unspecified

        Monitored:
          type: integer
          description: Whether the bus is currently monitored by the system.
          enum:
            - 1
            - 0
          x-satay:
            parse-as: bool

    BusStopsResponse:
      type: object
      additionalProperties: false
      required:
        - odata.metadata
        - value
      properties:
        odata.metadata:
          type: string
          format: uri
          description: OData metadata URL.
          x-satay:
            ignore: true

        value:
          type: array
          description: Bus stops in this response page.
          items:
            $ref: "#/components/schemas/BusStop"

    BusStop:
      type: object
      additionalProperties: false
      required:
        - BusStopCode
        - RoadName
        - Description
        - Latitude
        - Longitude
      properties:
        BusStopCode:
          $ref: "#/components/schemas/BusStopCode"

        RoadName:
          type: string
          description: Road on which the bus stop is located.

        Description:
          type: string
          description: Bus stop landmark or location description.
          x-satay:
            identifier: desc

        Latitude:
          type: number
          format: double
          description: Latitude of the bus stop.
          x-satay:
            identifier: lat

        Longitude:
          type: number
          format: double
          description: Longitude of the bus stop.
          x-satay:
            identifier: long

    TrafficImagesResponse:
      type: object
      additionalProperties: false
      required:
        - odata.metadata
        - value
      properties:
        odata.metadata:
          type: string
          format: uri
          description: OData metadata URL.
          x-satay:
            ignore: true

        value:
          type: array
          description: Traffic camera images in this response page.
          items:
            $ref: "#/components/schemas/TrafficImage"

    TrafficImage:
      type: object
      additionalProperties: false
      required:
        - CameraID
        - Latitude
        - Longitude
        - ImageLink
      properties:
        CameraID:
          type: string
          description: Numeric identifier of the traffic camera.
          example: "1001"
          x-satay:
            parse-as: u32

        Latitude:
          type: number
          format: double
          description: Latitude of the traffic camera.
          x-satay:
            identifier: lat

        Longitude:
          type: number
          format: double
          description: Longitude of the traffic camera.
          x-satay:
            identifier: long

        ImageLink:
          type: string
          format: uri
          description: URL of the latest image from the traffic camera.
          x-satay:
            identifier: image-link

    TrafficSpeedBandsResponse:
      type: object
      additionalProperties: false
      required:
        - odata.metadata
        - lastUpdatedTime
        - value
      properties:
        odata.metadata:
          type: string
          format: uri
          description: OData metadata URL.
          x-satay:
            ignore: true

        lastUpdatedTime:
          type: string
          description: Time at which the speed-band data was last updated.
          x-satay:
            ignore: true

        value:
          type: array
          description: Traffic speed bands in this response page.
          items:
            $ref: "#/components/schemas/TrafficSpeedBand"

    TrafficSpeedBand:
      type: object
      additionalProperties: false
      required:
        - LinkID
        - RoadName
        - RoadCategory
        - SpeedBand
        - MinimumSpeed
        - MaximumSpeed
        - StartLon
        - StartLat
        - EndLon
        - EndLat
      properties:
        LinkID:
          type: string
          description: Numeric identifier of the road link.
          x-satay:
            parse-as: u64

        RoadName:
          type: string
          description: Name of the road.

        RoadCategory:
          $ref: "#/components/schemas/RoadCategory"

        SpeedBand:
          type: integer
          description: Speed-band number assigned to the road link.
          x-satay:
            integer-type: u8

        MinimumSpeed:
          type: string
          description: Lower speed bound in kilometres per hour.
          x-satay:
            identifier: min-speed
            parse-as: u16

        MaximumSpeed:
          type: string
          description: Upper speed bound in kilometres per hour.
          x-satay:
            identifier: max-speed
            parse-as: u16

        StartLon:
          type: string
          description: Longitude of the road link's start point.
          x-satay:
            parse-as: f64

        StartLat:
          type: string
          description: Latitude of the road link's start point.
          x-satay:
            parse-as: f64

        EndLon:
          type: string
          description: Longitude of the road link's end point.
          x-satay:
            parse-as: f64

        EndLat:
          type: string
          description: Latitude of the road link's end point.
          x-satay:
            parse-as: f64

    RoadCategory:
      description: Classification of the road carrying the traffic-speed reading.
      anyOf:
        - type: string
        - type: string
          enum:
            - A
            - B
            - C
            - D
            - E
            - F
            - G
          x-satay:
            enum-variants:
              A: Expressway
              B: MajorArterialRoads
              C: ArterialRoads
              D: MinorArterialRoads
              E: SmallRoads
              F: SlipRoads
              G: NoCategoryInfoAvail

    TrafficIncidentsResponse:
      type: object
      additionalProperties: false
      required:
        - odata.metadata
        - value
      properties:
        odata.metadata:
          type: string
          format: uri
          description: OData metadata URL.
          x-satay:
            ignore: true

        value:
          type: array
          description: Traffic incidents in this response page.
          items:
            $ref: "#/components/schemas/TrafficIncident"

    TrafficIncident:
      type: object
      additionalProperties: false
      required:
        - Type
        - Latitude
        - Longitude
        - Message
      properties:
        Type:
          $ref: "#/components/schemas/IncidentType"
          x-satay:
            identifier: incident-type

        Latitude:
          type: number
          format: double
          description: Latitude of the traffic incident.
          x-satay:
            identifier: lat

        Longitude:
          type: number
          format: double
          description: Longitude of the traffic incident.
          x-satay:
            identifier: long

        Message:
          type: string
          description: Human-readable description of the traffic incident.
          x-satay:
            identifier: msg

    IncidentType:
      description: Type of traffic incident.
      anyOf:
        - type: string
        - type: string
          description: Known incident type spellings.
          enum:
            - Accident
            - Road Works
            - Vehicle breakdown
            - Weather
            - Obstacle
            - Road Block
            - Heavy Traffic
            - Misc.
            - Diversion
            - Unattended Vehicle
            - Roadwork
          x-satay:
            enum-variants:
              "Road Works": RoadWorks
              "Vehicle breakdown": VehicleBreakdown
              "Road Block": RoadBlock
              "Heavy Traffic": HeavyTraffic
              "Misc.": Misc
              "Unattended Vehicle": UnattendedVehicle

    TaxiAvailabilityResponse:
      type: object
      additionalProperties: false
      required:
        - odata.metadata
        - value
      properties:
        odata.metadata:
          type: string
          format: uri
          description: OData metadata URL.
          x-satay:
            ignore: true

        value:
          type: array
          description: Coordinates of available taxis in this response page.
          items:
            $ref: "#/components/schemas/Coordinates"

    Coordinates:
      type: object
      additionalProperties: false
      required:
        - Latitude
        - Longitude
      properties:
        Latitude:
          type: number
          format: double
          description: Latitude of the taxi.
          x-satay:
            identifier: lat

        Longitude:
          type: number
          format: double
          description: Longitude of the taxi.
          x-satay:
            identifier: long

    FacilitiesMaintenanceResponse:
      type: object
      additionalProperties: false
      required:
        - odata.metadata
        - value
      properties:
        odata.metadata:
          type: string
          format: uri
          description: OData metadata URL.
          x-satay:
            ignore: true

        value:
          type: array
          description: Facility maintenance data files for the queried station.
          items:
            $ref: "#/components/schemas/FacilityMaintenanceLink"

    FacilityMaintenanceLink:
      type: object
      additionalProperties: false
      required:
        - Link
      properties:
        Link:
          type: string
          format: uri
          description: URL of the facility maintenance data file for the queried station.

        TimeStamp:
          type: string
          format: date-time
          description: Time at which the facility maintenance data was last updated.
          x-satay:
            ignore: true

    StationCode:
      description: MRT/LRT station code.
      type: string
      enum:
        - NS1
        - NS2
        - NS3
        - NS3A
        - NS4
        - NS5
        - NS6
        - NS7
        - NS8
        - NS9
        - NS10
        - NS11
        - NS12
        - NS13
        - NS14
        - NS15
        - NS16
        - NS17
        - NS18
        - NS19
        - NS20
        - NS21
        - NS22
        - NS23
        - NS24
        - NS25
        - NS26
        - NS27
        - NS28
        - EW1
        - EW2
        - EW3
        - EW4
        - EW5
        - EW6
        - EW7
        - EW8
        - EW9
        - EW10
        - EW11
        - EW12
        - EW13
        - EW14
        - EW15
        - EW16
        - EW17
        - EW18
        - EW19
        - EW20
        - EW21
        - EW22
        - EW23
        - EW24
        - EW25
        - EW26
        - EW27
        - EW28
        - EW29
        - EW30
        - EW31
        - EW32
        - EW33
        - CG
        - CG1
        - CG2
        - NE1
        - NE2
        - NE3
        - NE4
        - NE5
        - NE6
        - NE7
        - NE8
        - NE9
        - NE10
        - NE11
        - NE12
        - NE13
        - NE14
        - NE15
        - NE16
        - NE17
        - CC1
        - CC2
        - CC3
        - CC4
        - CC5
        - CC6
        - CC7
        - CC8
        - CC9
        - CC10
        - CC11
        - CC12
        - CC13
        - CC14
        - CC15
        - CC16
        - CC17
        - CC18
        - CC19
        - CC20
        - CC21
        - CC22
        - CC23
        - CC24
        - CC25
        - CC26
        - CC27
        - CC28
        - CC29
        - CC30
        - CC31
        - CC32
        - CC33
        - CC34
        - CE1
        - CE2
        - DT1
        - DT2
        - DT3
        - DT4
        - DT5
        - DT6
        - DT7
        - DT8
        - DT9
        - DT10
        - DT11
        - DT12
        - DT13
        - DT14
        - DT15
        - DT16
        - DT17
        - DT18
        - DT19
        - DT20
        - DT21
        - DT22
        - DT23
        - DT24
        - DT25
        - DT26
        - DT27
        - DT28
        - DT29
        - DT30
        - DT31
        - DT32
        - DT33
        - DT34
        - DT35
        - DT36
        - DT37
        - DE1
        - DE2
        - TE1
        - TE2
        - TE3
        - TE4
        - TE5
        - TE6
        - TE7
        - TE8
        - TE9
        - TE10
        - TE11
        - TE12
        - TE13
        - TE14
        - TE15
        - TE16
        - TE17
        - TE18
        - TE19
        - TE20
        - TE21
        - TE22
        - TE22A
        - TE23
        - TE24
        - TE25
        - TE26
        - TE27
        - TE28
        - TE29
        - TE30
        - TE31
        - TE32
        - BP1
        - BP2
        - BP3
        - BP4
        - BP5
        - BP6
        - BP7
        - BP8
        - BP9
        - BP10
        - BP11
        - BP12
        - BP13
        - BP14
        - STC
        - SE1
        - SE2
        - SE3
        - SE4
        - SE5
        - SW1
        - SW2
        - SW3
        - SW4
        - SW5
        - SW6
        - SW7
        - SW8
        - PTC
        - PE1
        - PE2
        - PE3
        - PE4
        - PE5
        - PE6
        - PE7
        - PW1
        - PW2
        - PW3
        - PW4
        - PW5
        - PW6
        - PW7
        # Future lines and extensions, announced with official codes by LTA.
        - CR1
        - CR2
        - CR3
        - CR4
        - CR5
        - CR6
        - CR7
        - CR8
        - CR9
        - CR10
        - CR11
        - CR12
        - CR13
        - CR14
        - CR15
        - CR16
        - CR17
        - CR18
        - CR19
        - CR20
        - CR21
        - CR22
        - CR23
        - CP1
        - CP2
        - CP3
        - CP4
        - JS1
        - JS2
        - JS2A
        - JS3
        - JS4
        - JS5
        - JS6
        - JS7
        - JS8
        - JS9
        - JS10
        - JS11
        - JS12
        - JW1
        - JW2
        - JW3
        - JW4
        - JW5
        - JE1
        - JE2
        - JE3
        - JE4
        - JE5
        - JE6
        - JE7
